[general]
import = [
  # Windows-specific settings
  "~\\AppData\\Roaming\\alacritty\\windows.toml",
]

[window]
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[colors.primary]
background = "#000000"

[mouse]
bindings = [
  { mouse = "Right", action = "Paste" },
]
