[manager]
show_hidden = true

[opener]
play = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = "nvim %*", block = true, for = "windows" },
]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = "nvim %*", block = true, for = "windows" },
]
open = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = "nvim %*", block = true, for = "windows" },
]
