theme = "vscody"

[editor]
line-number = "relative"
cursorline = true
true-color = true
rulers = [120]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "all"
nbsp = "all"
nnbsp = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
# tab = "→"
# tabpad = "→"
tab = "―"
tabpad = "―"
newline = "⏎"

[editor.indent-guides]
render = false
skip-levels = 1
# character = "╎"
# character = "┆"
character = "┊"
# character = "⸽"

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-c = "normal_mode" # Maps Ctrl-c to force normal mode (kinda like Escape)
# C-z = "undo"
# "C-ù" = "toggle_line_comments"
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
G = ["goto_last_line"]
# a = "insert_mode"
# i = "move_line_up"
# j = "move_char_left"
# k = "move_line_down"

[keys.insert]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-c = "normal_mode" # Maps Ctrl-c to enter normal mode
# C-z = "undo"
# "C-ù" = "toggle_line_comments"
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
